languageCode = "en-us"
title = "Hiro's Stuff"
theme = "rose-pine"
baseURL = "https://protagon.space"

[params]
    subtitle = "Valentin Boettcher's Site"
    dateFmt = "02.01.2006 15:04"
    about = "/about"
    author = "Valentin Boettcher"
    user = "hiro"
    hostname = "protagon.space"

[menu]
  [[menu.header]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 1

  [[menu.header]]
        identifier = "Posts"
        name = "Posts"
        url = "/posts/"
        weight = 2

  [[menu.header]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 3



[permalinks]
  posts = "/:year/:month/:title/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = "rose-pine-dawn"

[[params.social]]
key = 1
name = "email"
url = "mailto:change-me-or-go-to-spam@protagon.space"

[[params.social]]
key = 2
name = "git"
url = "https://git.protagon.space"

[[params.social]]
key = 3
name = "github"
url = "https://github.com/vale981"

[[params.social]]
key = 4
name = "(old) music"
url = "https://afa-music.bandcamp.com/"

[[params.social]]
key = 5
name = "gpg"
url = "/contact"
